CREATE DATABASE Panopticon
USE Panopticon

CREATE TABLE CCTV_Data(
CCTV_ID UNIQUEIDENTIFIER NOT NULL,
Current_People INT,
CTime DATETIME,
Max_People_At_Last_Hour INT,
)
SELECT * FROM CCTV_Current_Data

